// RootLayout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components";
import Header from "./components/header/Header";
import Banner from "./components/Banner";
import CategoryList from "./components/CategoryList";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Navbar />
        <div className="flex mt-6 mx-auto max-w-[1280px] px-5 md:px-8">
          <div className="flex flex-col md:flex-row w-full md:space-x-6 justify-between">
            <div className="hidden md:flex md:w-1/4">
              <CategoryList />
            </div>
            <div className="md:w-3/4">
              <Banner />
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
